# Generated by Django 4.2.5 on 2023-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=500)),
                ('malumot', models.TextField(max_length=5000)),
            ],
        ),
    ]
